{{- if and .Values.controller.enabled .Values.controller.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "lissto.fullname" . }}-controller-manager
  labels:
    {{- include "lissto.controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - env.lissto.dev
  resources:
  - blueprints
  - envs
  - lisstosecrets
  - lisstovariables
  - stacklifecycles
  - stacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - env.lissto.dev
  resources:
  - blueprints/finalizers
  - stacklifecycles/finalizers
  - stacks/finalizers
  verbs:
  - update
- apiGroups:
  - env.lissto.dev
  resources:
  - blueprints/status
  - envs/status
  - lisstosecrets/status
  - lisstovariables/status
  - stacklifecycles/status
  - stacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}

