{{- if .Values.bot.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lissto.fullname" . }}-bot
  namespace: {{ include "lissto.namespace" . }}
  labels:
    {{- include "lissto.bot.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lissto.fullname" . }}-bot
subjects:
- kind: ServiceAccount
  name: {{ include "lissto.fullname" . }}-bot
  namespace: {{ include "lissto.namespace" . }}
{{- end }}

