{{- if and .Values.bot.enabled (not .Values.bot.slack.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lissto.fullname" . }}-bot
  namespace: {{ include "lissto.namespace" . }}
  labels:
    {{- include "lissto.bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  slack-bot-token: {{ .Values.bot.slack.botToken | quote }}
  slack-app-token: {{ .Values.bot.slack.appToken | quote }}
  slack-signing-secret: {{ .Values.bot.slack.signingSecret | default "" | quote }}
{{- end }}

