{{- if .Values.bot.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lissto.fullname" . }}-bot
  namespace: {{ include "lissto.namespace" . }}
  labels:
    {{- include "lissto.bot.labels" . | nindent 4 }}
{{- end }}

