apiVersion: v1
entries:
  lissto:
  - apiVersion: v2
    appVersion: latest
    created: "2025-12-25T00:20:13.842153677Z"
    description: A Helm chart for Lissto - Kubernetes stack management platform
    digest: 93347b0178c4e65f8ae1e2174233e1481b52c97342ba77b1c976f42b129777dc
    home: https://github.com/lissto-dev/lissto
    keywords:
    - lissto
    - kubernetes
    - stack-management
    - docker-compose
    maintainers:
    - email: team@lissto.dev
      name: Lissto Team
    name: lissto
    sources:
    - https://github.com/lissto-dev/controller
    - https://github.com/lissto-dev/api
    - https://github.com/lissto-dev/slack-bot
    type: application
    urls:
    - https://github.com/lissto-dev/lissto-helm/releases/download/v0.1.2/lissto-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: latest
    created: "2025-12-24T02:19:05.861204015Z"
    description: A Helm chart for Lissto - Kubernetes stack management platform
    digest: e7cc168be541a2ac39840620da05d3af754ba691bb9e2f82647ef5db77eac854
    home: https://github.com/lissto-dev/lissto
    keywords:
    - lissto
    - kubernetes
    - stack-management
    - docker-compose
    maintainers:
    - email: team@lissto.dev
      name: Lissto Team
    name: lissto
    sources:
    - https://github.com/lissto-dev/controller
    - https://github.com/lissto-dev/api
    - https://github.com/lissto-dev/slack-bot
    type: application
    urls:
    - https://github.com/lissto-dev/lissto-helm/releases/download/v0.1.1/lissto-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: latest
    created: "2025-12-24T01:04:25.088736286Z"
    description: A Helm chart for Lissto - Kubernetes stack management platform
    digest: 58cebff1eb67bf63678525ec9151ce062c1442cd1d6c849c5d5f8e8d30047644
    home: https://github.com/lissto-dev/lissto
    keywords:
    - lissto
    - kubernetes
    - stack-management
    - docker-compose
    maintainers:
    - email: team@lissto.dev
      name: Lissto Team
    name: lissto
    sources:
    - https://github.com/lissto-dev/controller
    - https://github.com/lissto-dev/api
    - https://github.com/lissto-dev/slack-bot
    type: application
    urls:
    - https://github.com/lissto-dev/lissto-helm/releases/download/v0.1.0/lissto-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-25T00:20:13.840929698Z"
