apiVersion: v1
entries:
  lissto:
  - apiVersion: v2
    appVersion: latest
    created: "2025-12-23T21:05:28.168363127Z"
    description: A Helm chart for Lissto - Kubernetes stack management platform
    digest: 08bfa1aad0ce470ba80acd32f320b5207dc48ca0ad4931e94a4349a04016f16c
    home: https://github.com/lissto-dev/lissto
    keywords:
    - lissto
    - kubernetes
    - stack-management
    - docker-compose
    maintainers:
    - email: team@lissto.dev
      name: Lissto Team
    name: lissto
    sources:
    - https://github.com/lissto-dev/controller
    - https://github.com/lissto-dev/api
    - https://github.com/lissto-dev/slack-bot
    type: application
    urls:
    - https://lissto-dev.github.io/lissto/charts/lissto-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-23T21:05:28.167175247Z"
