{{- if and .Values.api.enabled .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "lissto.fullname" . }}-api
  namespace: {{ include "lissto.namespace" . }}
  labels:
    {{- include "lissto.api.labels" . | nindent 4 }}
spec:
  {{- if .Values.api.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.api.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.api.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lissto.api.selectorLabels" . | nindent 6 }}
{{- end }}



