{{- if and .Values.api.enabled .Values.api.apiKeys (not .Values.api.apiKeys.existingSecret) .Values.api.apiKeys.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lissto.fullname" . }}-api-keys
  namespace: {{ include "lissto.namespace" . }}
  labels:
    {{- include "lissto.api.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-keys.yaml: |
    {{- .Values.api.apiKeys.config | nindent 4 }}
{{- end }}

