{{- if .Values.api.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lissto.fullname" . }}-api
  namespace: {{ include "lissto.namespace" . }}
  labels:
    {{- include "lissto.api.labels" . | nindent 4 }}
  {{- if .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.api.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}

